# Generated by Django 4.2.2 on 2023-06-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=6, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('total_price', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
